version: '3'
services:
  flask-api:
    build: ./flask-api 
    ports:
      - "5000:5000"  
    volumes:
      - ./input:/app/input  
      - ./output:/app/output  

  bittorrent:
    image: ubuntu:20.04  
    volumes:
      - ./input:/models  
    command: >
      bash -c "apt-get update && apt-get install -y bittorrent && rm -rf /var/lib/apt/lists/* && \
      echo 'd10:magnet-uri26:magnet:?xt=urn:btih:magnet:?xt=urn:btih:3f8016061132ad4a475eb33dac569f3a88418974&dn=v1-5-pruned-emaonly.safetensors&tr=udp%3a%2f%2fopen.demonii.com%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce' > model.torrent && \
      bittorrent download model.torrent && \
      rm model.torrent"

volumes:
  input:
  output:
