version: '3'
services:
  myservice:
    build: .
    volumes:
      - /path/to/host/input:/host/tmp/input
      - /path/to/host/output:/host/tmp/output
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
